name: insect-pest-env
channels:
  - conda-forge
  - anaconda
  - nvidia
  - pytorch
dependencies:
  - numpy
  - matplotlib
  - pandas
  - pytorch=1.11.0=py3.9_cuda11.3_cudnn8.2.0_0
  - nvidia::cudatoolkit
  - pip
  - pillow
  - pytorch::torchvision
  - tqdm
  - wandb